version: 2
jobs:
  build:
    working_directory: ~/android-code
    docker:
      - image: circleci/android:api-26-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
              key: jars-{{ checksum "build.gradle" }}-{{ checksum  "test-app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "test-app/build.gradle" }}
  test_api_version_25:
    working_directory: ~/android-code
    docker:
      - image: circleci/android:api-26-alpha
    environment:
      JVM_OPTS: -Xmx3200m
      JAVA_OPTIONS: -Djava.io.tmpdir=/var/tmp
    steps:
      - checkout
      - run:
          name: List emulators
          command: avdmanager list
      - run:
          name: List SDK
          command: sdkmanager --list
      - run:
          name: Setup emulator
          command: sdkmanager "system-images;android-25;google_apis;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-25;google_apis;armeabi-v7a"
      - run:
          name: Launch emulator
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel on
          background: true
      - run:
          name: Wait emulator
          command: |
            # wait for it to have booted
            circle-android wait-for-boot
            # unlock the emulator screen
            sleep 30
            adb shell input keyevent 82
      - run:
          name: Unit testing
          command: ./gradlew testAllModulesTravis
      - store_artifacts:
          path: test-app/build/reports
          destination: reports
      - store_test_results:
          path: test-app/build/test-results              

  test_api_version_17:
    working_directory: ~/android-code
    docker:
      - image: circleci/android:api-26-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Setup emulator
          command: sdkmanager "system-images;android-17;default;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-17;default;armeabi-v7a"
      - run:
          name: Launch emulator
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel on
          background: true        
      - run:
          name: Wait emulator
          command: |
            # wait for it to have booted
            circle-android wait-for-boot
            # unlock the emulator screen
            sleep 30
            adb shell input keyevent 82
      - run:
          name: Run Tests
          command: ./gradlew testAllModulesTravis
      - store_artifacts:
          path: test-app/build/reports
          destination: reports
      - store_test_results:
          path: test-app/build/test-results
workflows:
  version: 2
  build_test:
    jobs:
      - build
      - test_api_version_25:
          requires:
            - build
      - test_api_version_17:
          requires:
            - build
