version: 2
jobs:
  build:
    working_directory: ~/android-code
    docker:
      - image: circleci/android:api-26-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
              key: jars-{{ checksum "build.gradle" }}-{{ checksum  "test-app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "test-app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test

      - run:
          name: Start emulator
          command: $ANDROID_HOME/emulator/emulator -avd circleci-android24 -no-audio -no-window
          background: true
          environment:
            TERM: dumb

      - run:
          name: Wait for emulator
          command: ./android-wait-for-boot.sh
          environment:
            TERM: dumb

      - run:
          name: Remove lock screen
          command: adb shell input keyevent 82
          environment:
            TERM: dumb

      - run:
          name: Unit testing
          command: ./gradlew testAllModulesTravis
          environment:
            TERM: dumb
      - store_artifacts:
          path: test-app/build/reports
          destination: reports
      - store_test_results:
          path: test-app/build/test-results
